chain:
  bech32_prefix: gea
  modules: [
    "telemetry",
    "modules",
    "message_type",
    "messages",
    "actions",
    "auth",
    "bank",
    "task",
    "consensus",
    "wasm",
    "upgrade",
    "distribution",
    "feegrant",
    "wmint",
    "slashing",
    "staking",
    "gov",
    "wstaking",
    "did",
    "kyc",
    "wnft",
    "wbank",
    "sequencer",
    "rollapp",
    "dao",
    "wdistri",
    "evm",
    "transfer",
    "ante",
    "raw_block",
    "migrate",
    "ibc",
    "ibc_transfer",
    "nft",
    "committee",
    "tx_index",
    "anymsgs"
  ]
node:
  type: remote
  config:
    rpc:
      client_name: juno
      address: http://192.168.0.81:21657
      max_connections: 20
    grpc:
      address: 192.168.0.81:9190
      insecure: true

parsing:
  workers: 20
  start_height: 1
  average_block_time: 5s
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: true
database:
#   url: postgresql://pguser:pgpassword@postgres_gea_hub:5432/callisto-gea-hub?sslmode=disable&search_path=public
  url: postgresql://pguser:pgpassword@192.168.0.100:5433/callisto-gea-hub?sslmode=disable&search_path=public
  max_open_connections: 50
  max_idle_connections: 50
  partition_size: 1000000
  partition_batch: 1000

redis:
  url: redis://redis:6379/0

logging:
  level: info
  format: text
telemetry:
  port: 4321